#!/bin/bash
echo "Menyiapkan Installasi Web server"
sudo apt-get update
echo "Melakukan Installasi Webserver"
sudo apt-get install -y nginx php php-mysql
#proses setup website
sudo apt-get install -y unzip
wget https://github.com/sdcilsy/sosial-media/archive/master.zip
unzip master.zip
sudo rm -Rf /var/www/html/
mkdir -p /var/www/html
sudo mv sosial-media-master/* /var/www/html
echo "Setup selesai"
